package org.wit.charitymark.activities

import android.content.Intent
import android.net.Uri
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.text.BoringLayout.make
import android.view.Menu
import android.view.MenuItem
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import com.google.android.material.snackbar.Snackbar
import com.squareup.picasso.Picasso
import org.wit.charitymark.R
import org.wit.charitymark.databinding.ActivityCharitymarkBinding
import org.wit.charitymark.helpers.showImagePicker
import org.wit.charitymark.main.MainApp
import org.wit.charitymark.models.CharitymarkModel
import timber.log.Timber
import timber.log.Timber.i

class CharitymarkActivity : AppCompatActivity() {
    // ActivityCharitymarkBinding class is an autogenerated class
    // Import to access the View objects on layout (activity_charitymark.xml).
    private lateinit var binding: ActivityCharitymarkBinding
    // creating a charitymark as a class member (used in event handler btnAdd.setOnClickListener)
    var charitymark = CharitymarkModel()
    lateinit var app: MainApp
    private lateinit var imageIntentLauncher : ActivityResultLauncher<Intent>
    val IMAGE_REQUEST = 1
    private lateinit var mapIntentLauncher : ActivityResultLauncher<Intent>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //ocal flag initialised to false:
        var edit = false

        // inflate our layout using this binding class
        binding = ActivityCharitymarkBinding.inflate(layoutInflater)
        setContentView(binding.root)
        // Enable toolbar (for cancelling a charity event before adding)
        binding.toolbarAdd.title = title
        setSupportActionBar(binding.toolbarAdd)

        app = application as MainApp
        i("Charitymark Activity started.")

        if (intent.hasExtra("charitymark_edit")) {
            //Set the flag to true if we have a charity event passed
            edit = true
            charitymark = intent.extras?.getParcelable("charitymark_edit")!!
            binding.charitymarkTitle.setText(charitymark.title)
            binding.description.setText(charitymark.description)
            // Save Charity event button label CharitymarkActivity is launched with a charity event passed to it.
            binding.btnAdd.setText(R.string.save_charitymark)
            Picasso.get()
                .load(charitymark.image)
                .into(binding.charitymarkImage)
            // If editing image - Change button label to be Change Image from Add Image.
            if (charitymark.image != Uri.EMPTY) {
                binding.chooseImage.setText(R.string.change_charitymark_image)
            }
        }

        // bind to the Button
        // Adding update functionality (when charity event selected from charity event list activity)
        binding.btnAdd.setOnClickListener() {
            charitymark.title = binding.charitymarkTitle.text.toString()
            charitymark.description = binding.description.text.toString()
            if (charitymark.title.isEmpty()) {
                Snackbar.make(it,R.string.enter_charitymark_title, Snackbar.LENGTH_LONG)
                    .show()
            } else {
                if (edit) {
                    app.charitymarks.update(charitymark.copy())
                } else {
                    app.charitymarks.create(charitymark.copy())
                }
            }
            i("add Button Pressed: $charitymark")
            setResult(RESULT_OK)
            finish()
        }
        // Event handler for image button
        binding.chooseImage.setOnClickListener {
            showImagePicker(imageIntentLauncher)
        }
        // Event handler for set location button
        binding.charitymarkLocation.setOnClickListener {
            i ("Set Location Pressed")
        }
        // Event handler for maps
        binding.charitymarkLocation.setOnClickListener {
            val launcherIntent = Intent(this, MapActivity::class.java)
            mapIntentLauncher.launch(launcherIntent)
        }

        //  initialise the callback function
        registerImagePickerCallback()
        registerMapCallback()
    }
    // inflate the menu_charitymark to display CANCEL menu on
    override fun onCreateOptionsMenu(menu: Menu): Boolean {
        menuInflater.inflate(R.menu.menu_charitymark, menu)
        return super.onCreateOptionsMenu(menu)
    }
    // handle the menu CANCEL event with this method
    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            R.id.item_cancel -> {
                finish()
            }
        }
        return super.onOptionsItemSelected(item)
    }

    private fun registerImagePickerCallback() {
        imageIntentLauncher =
            registerForActivityResult(ActivityResultContracts.StartActivityForResult())
            { result ->
                when(result.resultCode){
                    RESULT_OK -> {
                        if (result.data != null) {
                            i("Got Result ${result.data!!.data}")
                            charitymark.image = result.data!!.data!!
                            Picasso.get()
                                .load(charitymark.image)
                                .into(binding.charitymarkImage)
                        } // end of if
                    }
                    RESULT_CANCELED -> { } else -> { }
                }
            }
    }

    private fun registerMapCallback() {
        mapIntentLauncher =
            registerForActivityResult(ActivityResultContracts.StartActivityForResult())
            { i("Map Loaded") }
    }
}